services:
  backend:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    env_file:
      - .env
    command: >
      bash -c "
        poetry install --no-root &&
        poetry run ruff check &&
        poetry run mypy src/apps/ &&
        poetry run python manage.py migrate &&
        poetry run python manage.py test &&
        poetry run python manage.py runserver 0.0.0.0:8000 --verbosity 3
      "

  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - .env
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
