services:
  web:
    build: .
    working_dir: /app/educa
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: educa.settings
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      bash -c "
        cd /app/educa &&
        poetry run black . &&
        poetry run flake8 . &&
        poetry run mypy . &&
        poetry run python manage.py migrate &&
        poetry run python manage.py test &&
        poetry run python manage.py runserver 0.0.0.0:8000
      "

  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
