version: '3.8'

services:
  web:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "
        poetry run black . &&
        poetry run flake8 . &&
        poetry run pytest &&
        poetry run python manage.py runserver
      "
