input {
  file {
    path => "/logs/django.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "django-logs"
  }
}

filter {
  date {
    match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "django-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}