services:
  database:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - ../../.env

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  vault:
    image: vault:1.13.0
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_LOG_LEVEL: "info"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_LOCAL_CONFIG: '{
        "storage": {
          "file": {
            "path": "/vault/file"
          }
        },
        "listener": {
          "tcp": {
            "address": "0.0.0.0:8200",
            "tls_disable": true
          }
        },
        "disable_mlock": true,
        "ui": true,
        "audit": {
          "file": {
            "path": "/vault/logs/audit.log",
            "roll_size": "500MB",
            "roll_duration": "24h",
            "format": "json"
          }
        }
      }'
    volumes:
      - vault_data:/vault/file
      - vault_logs:/vault/logs
      - ./logs/vault:/vault/logs
    command: server
    restart: unless-stopped
    

volumes:
  vault_data:
    driver: local
  vault_logs: 
    driver: local
  postgres_data:
    driver: local
  